### ISSUE TITLE
[question] auto label error

### ISSUE THREAD

**Issue by luanon404** [beiyuouo/hcaptcha-model-factory#36]
**Question**
im using auto label but i always got value error

i saved image by `open(filename, "wb").write(bytes)` i think here is error?

**Expected behavior**
```

PS D:\python\hcaptcha-model-factory\src> py main.py new 
prompt[en] --> fish_underwater
2022-09-21 19:57:05 | DEBUG - Diagnose task | task_name=fish_underwater
Use AI to automatically label datasets? {'y', 'n'} --> y
please put all the images in the `unlabel` folder and press any key to continue...
2022-09-21 19:57:26 | INFO - Found 7 images in D:\python\hcaptcha-model-factory\data\fish_underwater\unlabel
2022-09-21 19:57:26 | DEBUG - Extracting embeddings...
2022-09-21 19:57:27 | INFO - Embeddings extracted
2022-09-21 19:57:27 | INFO - PCA..., shape of embs: (7, 512)
2022-09-21 19:57:27 | ERROR - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (8452), thread 'MainThread' (21844):
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    Fire(Scaffold)
  File "C:\Users\luanon404\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\luanon404\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
> File "C:\Users\luanon404\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\python\hcaptcha-model-factory\src\apis\scaffold.py", line 70, in new
    ClusterLabeler(data_dir=data_dir).run()
  File "D:\python\hcaptcha-model-factory\src\components\auto_label\cluster.py", line 65, in run
    self.embs = PCA(n_components=self.num_feat).fit_transform(self.embs)
  File "C:\Users\luanon404\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\decomposition\_pca.py", line 407, in fit_transform
    U, S, Vt = self._fit(X)
  File "C:\Users\luanon404\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\decomposition\_pca.py", line 457, in _fit
    return self._fit_full(X, n_components)
  File "C:\Users\luanon404\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\decomposition\_pca.py", line 475, in _fit_full
    raise ValueError(
ValueError: n_components=128 must be between 0 and min(n_samples, n_features)=7 with svd_solver='full'
```

**Desktop (please complete the following information):**

- OS: windows
- Version: latest

**Additional context**
![cf461699-6add-408a-aa9a-fd568c088c82](https://user-images.githubusercontent.com/71830807/191510461-64623cef-a640-47e4-86df-c0c9bf75cc66.png)
![ec656c58-afcb-4644-a09c-4a00f8c4f6c2](https://user-images.githubusercontent.com/71830807/191510465-193c24bc-5767-4c5b-92f7-45320b68b872.png)
![f13f04dd-7284-4cd8-9d25-609dbc2bd418](https://user-images.githubusercontent.com/71830807/191510467-7978561d-dcca-4b4a-a290-fe03f39ae50d.png)
![fc658142-4c28-4778-ab1e-4979bf283bcd](https://user-images.githubusercontent.com/71830807/191510471-02b63c51-3535-42c7-a544-b05c5ce09b83.png)
![0d903179-757d-4ef2-98d1-2b0bc25ef85d](https://user-images.githubusercontent.com/71830807/191510478-ebbb63ea-eec2-48f9-9644-27ccbf10cb2d.png)
![4c1633ef-a109-41ab-8f94-b6fd45efff6f](https://user-images.githubusercontent.com/71830807/191510482-2fba4880-53a9-4f29-a4a5-6ece0f7916d8.png)
![a37fb4c2-930f-45cd-81c7-e7798cc15693](https://user-images.githubusercontent.com/71830807/191510489-91e5421f-4377-4305-af74-c96bf366631a.png)

**Comment by beiyuouo** [comment]
I have fix it at [here](https://github.com/beiyuouo/hcaptcha-model-factory/commit/3190b6c386c6302f398fd31b0b65f5da53f313c2). You can pull the dev branch or manually modify to fix it. We will release it soon! Thanks a lot.
