### ISSUE TITLE
Validation: Split Error

### ISSUE THREAD

**Issue by Vinyzu** [beiyuouo/hcaptcha-model-factory#5]
Im getting this error:
```
Traceback (most recent call last):
  File "C:\Users\admin\Documents\GitHub\hcaptcha-model-factory\src\main.py", line 227, in <module>
    val()
  File "C:\Users\admin\Documents\GitHub\hcaptcha-model-factory\src\main.py", line 159, in val
    data = torchvision.datasets.ImageFolder(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\datasets\folder.py", line 310, in __init__
    super().__init__(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\datasets\folder.py", line 146, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\datasets\folder.py", line 190, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\datasets\folder.py", line 103, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes 0, 1. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp
```
When trying to validate my onnx model.
I tried splitting the data before, using another path, nothing worked.

**Comment by Vinyzu** [comment]
https://github.com/beiyuouo/hcaptcha-model-factory/pull/6
